import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Home( props ) {
  const {popular} = props
  
  



  return (


    <div className={styles.container}>
      <Head>
        <title>WPT-Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Popular Movies 
        </h1>
        
        <ul>
        {popular.movie_results.map((item,id)  => (
          <li key={id} className={styles.topmovies} >
          <h2 > {item.title} </h2> 
          <h3> {item.year} </h3>
          </li>
        ))}
        </ul>

        </main>

    
    </div>
  )
  
}

export const getStaticProps = async () => {
  const res = await fetch("https://movies-tvshows-data-imdb.p.rapidapi.com/?type=get-popular-movies&page=1&year=2020", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "movies-tvshows-data-imdb.p.rapidapi.com",
      "x-rapidapi-key": "2ddc4c8cb4msh0c9e366b10869f2p1df196jsn9f56ebef905e"
    }
  })
  
  const popular = await res.json()
  return {
    props: {
      popular
    }
  }
}

export default Home
