import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

 function Upcoming( {upcoming} ) {
  console.log(upcoming)
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Upcoming
        </h1>

        <>
        {
        upcoming.movie_results.map((item,id)  => (
        <div  key={id} className={styles.card} >
        <h2> {item.title} </h2> 
        <h3> {item.year} </h3>
        </div>
        ))
        }
        </>

        
      </main>

    
    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://movies-tvshows-data-imdb.p.rapidapi.com/?type=get-upcoming-movies&page=1", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "movies-tvshows-data-imdb.p.rapidapi.com",
      "x-rapidapi-key": "2ddc4c8cb4msh0c9e366b10869f2p1df196jsn9f56ebef905e"
    }
  })
  
  const upcoming = await res.json()
  return {
    props: {
      upcoming
    }
  }
}


export default Upcoming